language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty main'
  - sudo add-apt-repository -y 'ppa:george-edison55/cmake-3.x'
  - sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y clang-4.0 gcc-6 cmake

install:
  - BOOST_VERSION=1.60.0
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
  - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
  - mkdir -p ${BOOST_DIR}
  - travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}
  - CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir build && cd build && cmake .. && cmake --build .
