language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - develop
    - /^hotfix-.*$/
    - /^release-.*$/

before_install:
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-6.0 main'
  - sudo add-apt-repository -y 'ppa:george-edison55/cmake-3.x'
  - sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y clang-6.0 gcc-7 cmake

install:
  - wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT


script:
  - mkdir build && cd build && cmake .. && cmake --build . && ctest
